### ISSUE TITLE
Docs fail to build on crates.io

### ISSUE THREAD

**Issue by RossPorter506** [YuhanLiin/msp430fr2x5x-hal#18]
Thanks for the 0.4.0 update, though the docs [fail to build](https://docs.rs/crate/msp430fr2x5x-hal/0.4.0/builds/1656034) on crates.io. The logs make reference to the `x86_64-unknown-linux-gnu` target, and indeed running `cargo doc --target x86_64-unknown-linux-gnu` produces the same errors as those seen in the crates.io logs, namely: 

`"msp430-interrupt" is not a supported ABI for the current target`

The last version of the crates.io docs that [built successfully](https://docs.rs/crate/msp430fr2x5x-hal/0.2.3/builds/333991), 0.2.3, doesn't have this target argument. I presume at some point crates.io added `x86_64-unknown-linux-gnu` as a default target.

I checked against the RP2040 HAL, which has the following in their cargo.toml:

```toml
[package.metadata.docs.rs]
features = ["rt", "rom-v2-intrinsics", "defmt", "rtic-monotonic"]
targets = ["thumbv6m-none-eabi"]
```
I presume we need something similar?
